#!/usr/bin/env bash
#Script to compress archive of a MySQL dump of all databases.

# Set the MySQL root password
mysql_password = "$1"

# Generate the MySQL dump
mysqldump -u root -p${mysql_password} --all-databases > backup.sql

# Create the compressed archive
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
